# Python basics

This notebook provides an introduction to Python and is aimed at novice Python users. Course participants already skilled at programming in Python will probably choose to skip these exercises, although some parts might be useful as a refresher. 

Jupyter Notebooks (or simply 'notebook') provide a way to execute Python code in a web browser and will be used throughout this course. A notebook is subdivided into cells, which either have text or code. The code cells can easily be recognized as they are preceded by `In [ ]:` or `In [n]:` where `n` is a counter. To edit the code, select the cell by positioning your cursor in one of the code cells either by clicking the left mouse button or by navigating using the up and down arrow keys. Executing the code cell can be doen by clicking the Run button in the top menu of the notebook or, much easier, by holding the [shift] key and hitting [enter]. The output, preceded by `Out [n]:` (where n is a number), then appears below the code cell.

### Arithmetic

Because Python is an interpreted language, one of its uses is as a basic calculator. For example to compute 6 * 2 (remember, to execute this code, position the cursor in the code cell below and hit [shift][enter])

In [38]:
6 * 2 # Place the cursor here and hit [shift][enter]

12

The spaces are added to make the code more readable. `6*2` would work just as well, but it is not as easy to read and is therefore considered not to be proper style. The example above also shows how single-line comments can be included by typing text behind a `#` sign. Python will ignore any code typed on this line after the comment sign.

Exponentiation is performed by using **

In [11]:
2 ** 6

64

Values may be stored in variables, which can then be used to perform arithmetic operations just like numbers

In [12]:
a = 6
b = 2
a * b 

12

Python is case sensitive, so a variable with the name `a` is not the same as `A`

### Lists and Dictionaries

A `list` is a Python data structure that contains a collection of data that can be of any type. It is defined by typing the elements of the list separated by commas and enclosed by square brackets. The following list contains a string, integer and a float

In [39]:
alist = ['Darcy', 0, 2.3]
print(alist)

['Darcy', 0, 2.3]


Individual items in a list can be accessed by specifying their indices in the list between square brackets. Selecting elements like this is called *slicing*. Because Python always starts counting from 0, the first element in the list has index number 0 (this takes a little getting used to!). Multiple items can be selected by specifying the first and last index seperated by a colon

In [14]:
print(alist[0])
print(alist[0:2]) # Returns items 0 and 1, not 2!

Darcy
['Darcy', 0]


Note that the second line only returns items 0 and 1, not 2. This is because of the way counting works in Python: It starts at zero and then stops *before* the last number is reached. 

The first item in `alist` can be changed in the following way

In [40]:
alist[0] = 'Dupuit'
print(alist)

['Dupuit', 0, 2.3]


 The `+` operator can be used to combine two lists

In [43]:
a = (1, 2, 3)
b = (5, 10, 15)
print(a + b)

(1, 2, 3, 5, 10, 15)


The use of the `+` sign with lists does not imply an arithmetic operation! If the intent is to add the numbers, the lists must first be converted to `arrays`, which will be discussed below.

A *dictionary* is another Python data type that stores a set of variables. It is defined in the following way

In [44]:
adict = {'k': 10, 'S': 1e-5}

A big advantage of dictionaries is that individual values are accesed by using the name of a *key*, rather than a number

In [45]:
print(adict['k'])

10


### Loops and conditional statements

In Python, a `for` loop, i.e. a set of programming commands that is executed several times, is based on a `list`, or another iterable datatype. The code will iterate over all the items in the list, starting with the first. The number of steps of the `for` loop thus depends on the number of items in the list. 

There are a number of syntax rules for defining a `for` loop. First, a colon (`:`) must always terminate the line with the `for` keyword, and second, the lines of code that must be executed during each step of the loop must all be indented. This is illustrated in the following example, in which the variable `al` takes on the value of each element in the list `alist` during the for loop. The second, indented line tells Python to print the value of `a1` for each step of the loop

In [46]:
for al in alist:
    print(al)

Dupuit
0
2.3
12


There is no explicit statement that marks the end of the code statements that should be executed during the loop. Instead, Python's interpreter infers this based on the indentation. Proper indentation is thus absolutely essential as it controls the way the code behaves. This helps tremendously in creating neat, readable scripts. The length of the indentation is arbitrary, as long as it remains the same (the default is four spaces). 

Looping over the elements of a list is a very 'pythonic' way of doing things. Programmers using other languages may be used to loops that get executed a certain number of times. This is possible too and is typically done using the `range` class. In the following example `range(4)` creates 4 numbers, from 0 up to (but not including, because of the way Python counts) 4

In [47]:
for i in range(4):
    print('Step', i)

Step 0
Step 1
Step 2
Step 3


where `range` creates a sequence with numbers to iterate over.

Conditional statements (also called `if` statements) can be used to control the flow of the program depending on whether or not certain conditions are met. Just like with the `for` loop, a colon must be typed at the end of the line starting with `if`, and the lines that must be executed if the evaluated condition is true must be indented. There is no specific command to end the `if` statement, as with `for` loops it is inferred from the indentation.

In [48]:
t = -1
if (t < 0):
    print ("It is freezing!")

It is freezing!


### Arrays and NumPy

The core of Python includes the basic features of the language. All other features are included in separate *packages* (called libraries or toolboxes in other programming languages). The package for creating and manipulating arrays is called `numpy`. The `numpy` package also includes a set of very useful functions, including basic mathematical functions (`cos`, `exp`, `log`, `sum`, etc.).

Before a package can be used, it needs to be imported. The following line imports the `numpy` package and make sure it is recognized by the name `np`.

In [49]:
import numpy as np

All functions of the `numpy` package can now be called as `np.function_name()`. For example, a `list` can be converted to a NumPy `array` with the `np.array()` command. 

In [50]:
a = np.array([1, 2, 3, 4])

A two-dimensional array can be created by entering a list of rows, where each row is again a list that contains the column values for that row

In [51]:
A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Functions that work for individual numbers can also be used on arrays, for example `numpy`'s `sqrt` function

In [52]:
print('sqrt(a) gives:', np.sqrt(a))

sqrt(a) gives: [1.         1.41421356 1.73205081 2.        ]


Arithmetic operators can also be be used with arrays. The following code defines an array `b` and multiplies the elements of the arrays `a` and `b` element by element

In [53]:
b = np.array([2, 2, 3, 3])
print('a * b gives:', a * b)

a * b gives: [ 2  4  9 12]


Those working with matrices might have expected a different outcome: The dot product. The dot product of arrays `a` and `b` of length `N` (i.e., $\sum_{n=1}^N a_nb_n$, see Chapter/Appendix ###) is obtained by using the `@` operator

In [54]:
a @ b # Or, alternatively: np.dot(a,b)

27

Just like for a `list` the individual elements of an array can be accessed by indexing using square brackets (always remembering that the first index has number 0!). The following code examples show some of the various array slicing options

In [55]:
x = np.arange(7, 17) # Similar to the range function used before, instead this one creates a numpy array
print(x)
print(x[0])
print(x[0:5])
print(x[:5]) # result is the same as for the previous line
print(x[-5:]) # returns the last 5 values
print(x[3:7])
print(x[2:9:2]) # step is 2

[ 7  8  9 10 11 12 13 14 15 16]
7
[ 7  8  9 10 11]
[ 7  8  9 10 11]
[12 13 14 15 16]
[10 11 12 13]
[ 9 11 13 15]


Parts or values of an array may also be selected based on conditions. This is called *advanced slicing*. For example

In [56]:
print(x < 10)

[ True  True  True False False False False False False False]


More advanced code examples will be introduced during the course